## Pandas
 #### 1. Series

 A pandas series is a one dimensional array like object that can hold any data type. It similar to a column in a table.

In [5]:
import pandas as pd

data = [1, 2, 3, 4, 5, 6]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
data = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}

series_dict = pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
d    4
e    5
dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
data = [1, 2, 3, 4]
idx = ['a', 'b', 'c', 'd']

serie = pd.Series(data, index=idx)
print(serie)

a    1
b    2
c    3
d    4
dtype: int64

## Dataframe
DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.

In [3]:
import pandas as pd
data = {
    'Name' : ['Sahil', 'Manish', 'pratyush'],
    'Age' : [20, 19, 25],
    'city' : ['Kolkata', 'bihar', 'punjab']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age     city
0     Sahil   20  Kolkata
1    Manish   19    bihar
2  pratyush   25   punjab
<class 'pandas.core.frame.DataFrame'>

##### Create a Dataframe using Dictionaries

In [8]:
data = [
    {'Name' : 'Sahil', 'Age' : 20, 'city' : 'Kolkata'},
    {'Name' : 'Mani', 'Age' : 19, 'city' : 'bihar'},
    {'Name' : 'pratyush', 'Age' : 25, 'city' : 'punjab'},
]

df = pd.DataFrame(data)
print(df)

       Name  Age     city
0     Sahil   20  Kolkata
1      Mani   19    bihar
2  pratyush   25   punjab

In [9]:
df

       Name  Age     city
0     Sahil   20  Kolkata
1      Mani   19    bihar
2  pratyush   25   punjab

In [10]:
df['Name'] # it will convert to series because there is a single coloum

0       Sahil
1        Mani
2    pratyush
Name: Name, dtype: object

In [11]:
df.loc[0] #  select rows and columns based on their labels

Name      Sahil
Age          20
city    Kolkata
Name: 0, dtype: object

In [12]:
df.iloc[1] # when choosing rows and columns based on specific positions

Name     Mani
Age        19
city    bihar
Name: 1, dtype: object

#### Accessing a specified element

In [14]:
print(df.at[1, 'Age'])

19

In [17]:
print(df.iat[2, 2])

punjab

### Data Manipulation using dataframe

In [25]:
## Adding a new coloumn

df['Salary'] = [50000, 43455456, 7567456346]
df

       Name  Age     city      Salary
0     Sahil   20  Kolkata       50000
1      Mani   19    bihar    43455456
2  pratyush   25   punjab  7567456346

In [26]:
# Remove a coloumn 
df.drop('Salary', axis=1, inplace=True) # we have to give axis suppose we don't give any axis the it will take a axis as 0 why 1 because we have to remove coloumn inplace will remove the coloumn permanently
df

       Name  Age     city
0     Sahil   20  Kolkata
1      Mani   19    bihar
2  pratyush   25   punjab

In [27]:
df['Age'] = df['Age']+5
df

       Name  Age     city
0     Sahil   25  Kolkata
1      Mani   24    bihar
2  pratyush   30   punjab

In [28]:
df.drop(0, inplace=True)

In [29]:
df

       Name  Age    city
1      Mani   24   bihar
2  pratyush   30  punjab