## Data Encoding
     when a categorical data coverted into a numerical data it's called Data Encoding

#### One Hot Encoding
    A "OneHotEncoder" creates a new binary column for each unique category in a categorical feature, representing presence with a "1" and absence with a "0"

In [2]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [20]:
df = pd.DataFrame({
    'color' : ['red', 'green', 'blue', 'red', 'green', 'blue']
})

In [21]:
df

   color
0    red
1  green
2   blue
3    red
4  green
5   blue

In [22]:
encode = OneHotEncoder()

In [23]:
encoder = encode.fit_transform(df[['color']]).toarray()

In [24]:
encoder

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [25]:
encoded_df = pd.DataFrame(encoder, columns=encode.get_feature_names_out(['color']))

In [26]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0
5         1.0          0.0        0.0

In [30]:
encode.transform([['blue']]).toarray()

/home/sahil/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [31]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0
3    red         0.0          0.0        1.0
4  green         0.0          1.0        0.0
5   blue         1.0          0.0        0.0

#### Label Encoding
    "LabelEncoder" simply assigns a unique numerical value to each category, potentially implying an order even if none exists

In [3]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()

In [35]:
lbl_encoder.fit_transform(df[['color']])

/home/sahil/.local/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 2, 1, 0])

In [36]:
lbl_encoder.transform(['red'])

array([2])

#### Ordinal Encoding
    When we assing the ranks to the particular value and particular columns then we use ordinal encoder.

In [38]:
from sklearn.preprocessing import OrdinalEncoder

In [39]:
ordinal_encoder = OrdinalEncoder()

In [41]:
df = pd.DataFrame({
    'size' : ['small', 'medium', 'large', 'small', 'medium', 'large']
})
df

     size
0   small
1  medium
2   large
3   small
4  medium
5   large

In [42]:
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [43]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.]])

#### Target Guided Ordinal Encoding
    It is a technique which is used to encode categorical variable based on their relationship with the target variable. This encoding technique is usefull when we have categorical variable with a large numbr of unique categories.

In [4]:
import pandas as pd

In [53]:
df = pd.DataFrame({
    'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Los Angeles', 'Chicago'],
    'Price': [1000, 850, 750, 900, 800, 700]
})

df

          City  Price
0     New York   1000
1  Los Angeles    850
2      Chicago    750
3     New York    900
4  Los Angeles    800
5      Chicago    700

In [57]:
mean_price = df.groupby('City')['Price'].mean().to_dict()

In [58]:
mean_price

{'Chicago': 725.0, 'Los Angeles': 825.0, 'New York': 950.0}

In [59]:
df['City_Encoded'] = df['City'].map(mean_price)

In [61]:
df

          City  Price  City_Encoded
0     New York   1000         950.0
1  Los Angeles    850         825.0
2      Chicago    750         725.0
3     New York    900         950.0
4  Los Angeles    800         825.0
5      Chicago    700         725.0

In [62]:
df[['Price', 'City_Encoded']]

   Price  City_Encoded
0   1000         950.0
1    850         825.0
2    750         725.0
3    900         950.0
4    800         825.0
5    700         725.0

In [5]:
tip_df = pd.read_csv('../EDA/tip.csv')
tip_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
mean_totalbill = tip_df.groupby('time')['total_bill'].mean().to_dict()

In [7]:
mean_totalbill

{'Dinner': 20.79715909090909, 'Lunch': 17.168676470588235}

In [8]:
tip_df['time_encoded'] = tip_df['time'].map(mean_totalbill)

In [76]:
tip_df

     total_bill   tip     sex smoker   day    time  size  Time_Encoded
0         16.99  1.01  Female     No   Sun  Dinner     2     20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3     20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3     20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2     20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4     20.797159
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3     20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2     20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2     20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2     20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2     20.797159

[244 rows x 8 columns]