In [2]:
import pandas as pd 

df = pd.read_csv('../DataSet/update_flight_price.csv')

In [3]:
df.head(5)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Date_of_Journey
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,2006-11-18
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,2024-04-16
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,2005-04-20
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2023-10-06
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2001-08-24

In [4]:
df.tail(5)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Date_of_Journey
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2023-06-16
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,2015-07-28
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,2002-03-04
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,2004-03-06
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2004-09-21

In [5]:
df.drop('Unnamed: 0', inplace=True, axis=1)

In [6]:
df.head(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Date_of_Journey
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,2006-11-18
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,2024-04-16
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,2005-04-20
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2023-10-06
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2001-08-24

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
 11  Date_of_Journey   300153 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 27.5+ MB

In [8]:
df.drop('days_left', inplace=True, axis=1)

In [9]:
df.head(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,price,Date_of_Journey
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,5953,2006-11-18
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,5953,2024-04-16
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,5956,2005-04-20
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,5955,2023-10-06
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,5955,2001-08-24

In [10]:
df.shape

(300153, 11)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   price             300153 non-null  int64
 10  Date_of_Journey   300153 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 25.2+ MB

In [12]:
df.describe()

            duration          price
count  300153.000000  300153.000000
mean       12.221021   20889.660523
std         7.191997   22697.767366
min         0.830000    1105.000000
25%         6.830000    4783.000000
50%        11.250000    7425.000000
75%        16.170000   42521.000000
max        49.830000  123071.000000

In [13]:
df['Year'] = df['Date_of_Journey'].str.split('-').str[0]
df['Month'] = df['Date_of_Journey'].str.split('-').str[1]
df['Date'] = df['Date_of_Journey'].str.split('-').str[2]

In [14]:
df['Year'] = df['Year'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Date'] = df['Date'].astype(int)

In [15]:
df.head(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,price,Date_of_Journey,Year,Month,Date
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,5953,2006-11-18,2006,11,18
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,5953,2024-04-16,2024,4,16
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,5956,2005-04-20,2005,4,20
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,5955,2023-10-06,2023,10,6
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,5955,2001-08-24,2001,8,24

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   price             300153 non-null  int64
 10  Date_of_Journey   300153 non-null  object
 11  Year              300153 non-null  int64
 12  Month             300153 non-null  int64
 13  Date              300153 non-null  int64
dtypes: float64(1), int64(4), object(9)
memory usage: 32.1+ MB

In [17]:
df.drop('Date_of_Journey', inplace=True, axis=1)

In [18]:
df.head(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,price,Year,Month,Date
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,5953,2006,11,18
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,5953,2024,4,16
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,5956,2005,4,20
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,5955,2023,10,6
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,5955,2001,8,24

In [19]:
df.columns

Index(['airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'price',
       'Year', 'Month', 'Date'],
      dtype='object')

In [20]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,price,Year,Month,Date
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,5953,2006,11,18
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,5953,2024,4,16
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,5956,2005,4,20
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,5955,2023,10,6
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,5955,2001,8,24

In [21]:
df['arrival_time'].value_counts()

arrival_time
Night            91538
Evening          78323
Morning          62735
Afternoon        38139
Early_Morning    15417
Late_Night       14001
Name: count, dtype: int64

In [22]:
time_stamp = {
    'Early_Morning' : '12 : 10',
    'Morning' : '10 : 30',
    'Afternoon' : '13 : 45',
    'Evening' : '17 : 20',
    'Night' : '20 : 40',
    'Late_Night' : '23 : 45'
}
df['arrival_time'] = df['arrival_time'].map(time_stamp)

In [23]:
df.head(6)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,price,Year,Month,Date
0,SpiceJet,SG-8709,Delhi,Evening,zero,20 : 40,Mumbai,Economy,2.17,5953,2006,11,18
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,10 : 30,Mumbai,Economy,2.33,5953,2024,4,16
2,AirAsia,I5-764,Delhi,Early_Morning,zero,12 : 10,Mumbai,Economy,2.17,5956,2005,4,20
3,Vistara,UK-995,Delhi,Morning,zero,13 : 45,Mumbai,Economy,2.25,5955,2023,10,6
4,Vistara,UK-963,Delhi,Morning,zero,10 : 30,Mumbai,Economy,2.33,5955,2001,8,24
5,Vistara,UK-945,Delhi,Morning,zero,13 : 45,Mumbai,Economy,2.33,5955,2024,8,30

In [24]:
df['departure_time'].value_counts()

departure_time
Morning          71146
Early_Morning    66790
Evening          65102
Night            48015
Afternoon        47794
Late_Night        1306
Name: count, dtype: int64

In [25]:
df['departure_time'] = df['departure_time'].map(time_stamp)

In [26]:
df.head(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,price,Year,Month,Date
0,SpiceJet,SG-8709,Delhi,17 : 20,zero,20 : 40,Mumbai,Economy,2.17,5953,2006,11,18
1,SpiceJet,SG-8157,Delhi,12 : 10,zero,10 : 30,Mumbai,Economy,2.33,5953,2024,4,16
2,AirAsia,I5-764,Delhi,12 : 10,zero,12 : 10,Mumbai,Economy,2.17,5956,2005,4,20
3,Vistara,UK-995,Delhi,10 : 30,zero,13 : 45,Mumbai,Economy,2.25,5955,2023,10,6
4,Vistara,UK-963,Delhi,10 : 30,zero,10 : 30,Mumbai,Economy,2.33,5955,2001,8,24

In [27]:
df['arrival_hr'] = df['arrival_time'].str.split(":").str[0]
df['arrival_min'] = df['arrival_time'].str.split(":").str[1]

In [28]:
df.drop('arrival_time', inplace=True, axis=1)

In [29]:
df.head()

,airline,flight,source_city,departure_time,stops,destination_city,class,duration,price,Year,Month,Date,arrival_hr,arrival_min
0,SpiceJet,SG-8709,Delhi,17 : 20,zero,Mumbai,Economy,2.17,5953,2006,11,18,20,40
1,SpiceJet,SG-8157,Delhi,12 : 10,zero,Mumbai,Economy,2.33,5953,2024,4,16,10,30
2,AirAsia,I5-764,Delhi,12 : 10,zero,Mumbai,Economy,2.17,5956,2005,4,20,12,10
3,Vistara,UK-995,Delhi,10 : 30,zero,Mumbai,Economy,2.25,5955,2023,10,6,13,45
4,Vistara,UK-963,Delhi,10 : 30,zero,Mumbai,Economy,2.33,5955,2001,8,24,10,30

In [30]:
df['departure_hr'] = df['departure_time'].str.split(":").str[0]
df['departure_min'] = df['departure_time'].str.split(":").str[1]

In [31]:
df.drop('departure_time', inplace=True, axis=1)

In [32]:
df.head(5)

,airline,flight,source_city,stops,destination_city,class,duration,price,Year,Month,Date,arrival_hr,arrival_min,departure_hr,departure_min
0,SpiceJet,SG-8709,Delhi,zero,Mumbai,Economy,2.17,5953,2006,11,18,20,40,17,20
1,SpiceJet,SG-8157,Delhi,zero,Mumbai,Economy,2.33,5953,2024,4,16,10,30,12,10
2,AirAsia,I5-764,Delhi,zero,Mumbai,Economy,2.17,5956,2005,4,20,12,10,12,10
3,Vistara,UK-995,Delhi,zero,Mumbai,Economy,2.25,5955,2023,10,6,13,45,10,30
4,Vistara,UK-963,Delhi,zero,Mumbai,Economy,2.33,5955,2001,8,24,10,30,10,30

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   stops             300153 non-null  object
 4   destination_city  300153 non-null  object
 5   class             300153 non-null  object
 6   duration          300153 non-null  float64
 7   price             300153 non-null  int64
 8   Year              300153 non-null  int64
 9   Month             300153 non-null  int64
 10  Date              300153 non-null  int64
 11  arrival_hr        300153 non-null  object
 12  arrival_min       300153 non-null  object
 13  departure_hr      300153 non-null  object
 14  departure_min     300153 non-null  object
dtypes: float64(1), int64(4), object(10)
memory usage: 34.3+ MB

In [34]:
df['arrival_hr'] = df['arrival_hr'].astype(int)
df['arrival_min'] = df['arrival_min'].astype(int)
df['departure_hr'] = df['departure_hr'].astype(int)
df['departure_min'] = df['departure_min'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   stops             300153 non-null  object
 4   destination_city  300153 non-null  object
 5   class             300153 non-null  object
 6   duration          300153 non-null  float64
 7   price             300153 non-null  int64
 8   Year              300153 non-null  int64
 9   Month             300153 non-null  int64
 10  Date              300153 non-null  int64
 11  arrival_hr        300153 non-null  int64
 12  arrival_min       300153 non-null  int64
 13  departure_hr      300153 non-null  int64
 14  departure_min     300153 non-null  int64
dtypes: float64(1), int64(8), object(6)
memory usage: 34.3+ MB

In [35]:
df['stops'].value_counts()

stops
one            250863
zero            36004
two_or_more     13286
Name: count, dtype: int64

In [36]:
df['stops'].unique()

array(['zero', 'one', 'two_or_more'], dtype=object)

In [37]:
stops = {
    'zero' : '0',
    'one' : '1',
    'two_or_more' : '2'
}
df['stops'] = df['stops'].map(stops)

In [38]:
df['stops'].value_counts()

stops
1    250863
0     36004
2     13286
Name: count, dtype: int64

In [39]:
df.head(5)

,airline,flight,source_city,stops,destination_city,class,duration,price,Year,Month,Date,arrival_hr,arrival_min,departure_hr,departure_min
0,SpiceJet,SG-8709,Delhi,0,Mumbai,Economy,2.17,5953,2006,11,18,20,40,17,20
1,SpiceJet,SG-8157,Delhi,0,Mumbai,Economy,2.33,5953,2024,4,16,10,30,12,10
2,AirAsia,I5-764,Delhi,0,Mumbai,Economy,2.17,5956,2005,4,20,12,10,12,10
3,Vistara,UK-995,Delhi,0,Mumbai,Economy,2.25,5955,2023,10,6,13,45,10,30
4,Vistara,UK-963,Delhi,0,Mumbai,Economy,2.33,5955,2001,8,24,10,30,10,30

In [40]:
### if in duration we have data like 2h 54m then we use 
### df['duration'].str.split(" ").str[0].str.split('h').str[0]

df['duration'] = df['duration'].astype(str)
df['duration_hr'] = df['duration'].str.split(".").str[0]
df['duration_min'] = df['duration'].str.split(".").str[1]
df.head(2)

,airline,flight,source_city,stops,destination_city,class,duration,price,Year,Month,Date,arrival_hr,arrival_min,departure_hr,departure_min,duration_hr,duration_min
0,SpiceJet,SG-8709,Delhi,0,Mumbai,Economy,2.17,5953,2006,11,18,20,40,17,20,2,17
1,SpiceJet,SG-8157,Delhi,0,Mumbai,Economy,2.33,5953,2024,4,16,10,30,12,10,2,33

In [41]:
df.drop('duration', axis=1, inplace=True)

In [42]:
df.head(2)

,airline,flight,source_city,stops,destination_city,class,price,Year,Month,Date,arrival_hr,arrival_min,departure_hr,departure_min,duration_hr,duration_min
0,SpiceJet,SG-8709,Delhi,0,Mumbai,Economy,5953,2006,11,18,20,40,17,20,2,17
1,SpiceJet,SG-8157,Delhi,0,Mumbai,Economy,5953,2024,4,16,10,30,12,10,2,33

In [43]:
df['airline'].unique()

array(['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo',
       'Air_India'], dtype=object)

In [44]:
df['flight'].unique()

array(['SG-8709', 'SG-8157', 'I5-764', ..., '6E-7127', '6E-7259',
       'AI-433'], dtype=object)

In [45]:
df['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [46]:
df['destination_city'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [47]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [48]:
update = encoder.fit_transform(df[['airline', 'flight', 'source_city', 'destination_city']]).toarray()

In [49]:
update.shape

(300153, 1579)

In [50]:
update

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [51]:
columns = encoder.get_feature_names_out()

In [52]:
update_df = pd.DataFrame(update, columns=columns)

In [52]:
pd.concat([df, update_df], axis=1)

,airline,flight,source_city,stops,destination_city,class,price,Year,Month,Date,...,source_city_Delhi,source_city_Hyderabad,source_city_Kolkata,source_city_Mumbai,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai
0,SpiceJet,SG-8709,Delhi,0,Mumbai,Economy,5953,2006,11,18,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,SpiceJet,SG-8157,Delhi,0,Mumbai,Economy,5953,2024,4,16,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,AirAsia,I5-764,Delhi,0,Mumbai,Economy,5956,2005,4,20,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Vistara,UK-995,Delhi,0,Mumbai,Economy,5955,2023,10,6,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,Vistara,UK-963,Delhi,0,Mumbai,Economy,5955,2001,8,24,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,UK-822,Chennai,1,Hyderabad,Business,69265,2023,6,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
300149,Vistara,UK-826,Chennai,1,Hyderabad,Business,77105,2015,7,28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
300150,Vistara,UK-832,Chennai,1,Hyderabad,Business,79099,2002,3,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
300151,Vistara,UK-828,Chennai,1,Hyderabad,Business,81585,2004,3,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
300152,Vistara,UK-822,Chennai,1,Hyderabad,Business,81585,2004,9,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0