### 1.Upsampling Method

In [41]:
import pandas as pd 
import numpy as np

np.random.seed(123)

n_sample = 1000

class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [9]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=1, scale=2, size=n_class_1),
    'feature_2': np.random.normal(loc=1, scale=2, size=n_class_1),
    'target': [1] * n_class_1
})

In [10]:
class_0, class_1

(     feature_1  feature_2  target
 0    -0.471276   0.328462       0
 1     1.084072   1.038230       0
 2    -0.379223   1.147064       0
 3    -0.362274   0.638254       0
 4    -0.681071  -1.075766       0
 ..         ...        ...     ...
 895  -0.229982  -1.433189       0
 896  -0.533514  -0.370110       0
 897   0.060924  -0.284352       0
 898   1.041367   0.373888       0
 899  -0.862830   0.263030       0

 [900 rows x 3 columns],
     feature_1  feature_2  target
 0    0.551842  -1.194894       1
 1    1.677680  -0.883518       1
 2    0.456945   4.341879       1
 3    3.731062   1.135583       1
 4   -0.474748   4.261571       1
 ..        ...        ...     ...
 95   2.441381   0.956978       1
 96   0.898157   4.419586       1
 97   2.419568   3.649834       1
 98   0.635378   0.098474       1
 99   2.677820   1.481546       1

 [100 rows x 3 columns])

In [13]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [14]:
df.head(5)

   feature_1  feature_2  target
0  -0.471276   0.328462       0
1   1.084072   1.038230       0
2  -0.379223   1.147064       0
3  -0.362274   0.638254       0
4  -0.681071  -1.075766       0

In [15]:
df.tail(5)

     feature_1  feature_2  target
995   2.441381   0.956978       1
996   0.898157   4.419586       1
997   2.419568   3.649834       1
998   0.635378   0.098474       1
999   2.677820   1.481546       1

In [17]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [18]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [24]:
from sklearn.utils import resample

df_minority_upsamled = resample(df_minority, 
                                replace=True, 
                                n_samples=len(df_majority), 
                                random_state=123
                                )

In [23]:
df_minority_upsamled.shape

(900, 3)

In [26]:
df_minority_upsamled.head(5)

     feature_1  feature_2  target
966   3.324531   0.892048       1
992   1.644683   3.578339       1
998   0.635378   0.098474       1
917   1.754218  -1.711436       1
983   3.842592   5.054497       1

In [28]:
df_upsampled = pd.concat([df_majority, df_minority_upsamled])

In [29]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### 2.Downsampling Method

In [30]:
import pandas as pd 
import numpy as np

np.random.seed(123)

n_sample = 1000
class_ratio = 0.9
n_class_0 = int(n_sample * class_ratio)
n_class_1 = n_sample - n_class_0

In [33]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=1, scale=2, size=n_class_1),
    'feature_2': np.random.normal(loc=1, scale=2, size=n_class_1),
    'target': [1] * n_class_1
})

In [36]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [37]:
df.shape

(1000, 3)

In [38]:
df.head(5)

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [40]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [42]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [50]:
from sklearn.utils import resample

df_majority_downsampled = resample(df_majority, 
              replace=False,
              n_samples=len(df_minority),
              random_state=123)

In [51]:
df_majority_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [52]:
df_majority_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64